services:
  - type: web
    name: uon-smart-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: LIPANA_SECRET_KEY
        sync: false
      - key: LIPANA_ENV
        value: production
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: MPESA_PAYMENT_TYPE
        sync: false
      - key: MPESA_PAYMENT_NUMBER
        sync: false
      - key: MPESA_PAYMENT_NAME
        sync: false
      - key: NODE_VERSION
        value: 20.11.0
    autoDeploy: true
